### ISSUE TITLE
内存增长

### ISSUE THREAD

**Issue by MiniaturePepper** [jiangmingz/ReplayKit-iOS11-Recorder#1]
运动demo时，内存增长的很快啊，求解决方案

**Comment by jiangmingz** [comment]
![image](https://user-images.githubusercontent.com/187824/32816585-5ea99e34-c9f4-11e7-90d5-8a726b844aaf.png)
我 Demo 上没有看到内存增长。

**Comment by jiangmingz** [comment]
@MiniaturePepper 你怎么测试出来内存增长的。
